namespace: backend

replicas: 2

image:
  repository: th1alexandre/backend
  tag: latest
  pullPolicy: Always

containerPort: 8080

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    clusterIssuer: cloudflare-issuer
    rewriteTarget: /$1
    useRegex: "true"
  ingressClassName: nginx
  host: backend.p25.th1alexandre.uk
  path: /(.*)
  pathType: Static
  tlsSecretName: backend-tls
